export const path = {
  landingPage: '/landing',
  home: '/',
  vehicle: '/vehicle',
  battery: '/battery',
  login: '/login',
  register: '/register',
  profile: '/profile',
  post: '/post',
  payment: 'payment/result',
  updatePhone: '/update-phone',
  pricing: '/pricing',
  //account
  account: '/account',
  accountPosts: '/account/posts',
  accountNotification: '/account/notification',
  accountProfile: '/account/profile',
  accountUpdateProfile: 'updateProfile',
  accountPayment: '/account/payment',
  accountAddress: '/account/payment',
  accountChangePassword: '/account/password',
  accountPrivacySetting: '/setting/privacy',
  //admin
  admin: '/admin',
  adminPosts: '/admin/posts',
  adminDashboard: '/admin/dashboard',
  adminListings: '/admin/listings',
  adminUsers: '/admin/users',
  adminTransactions: '/admin/transactions',
  adminReports: '/admin/reports',
  adminSettings: '/admin/settings'
} as const
