export const path = {
  landingPage: '/',
  home: '/all',
  auction: '/auction',
  vehicle: '/vehicle',
  battery: '/battery',
  login: '/login',
  register: '/register',
  profile: '/profile',
  post: '/post',
  payment: '/payment/result',
  updatePhone: '/update-phone',
  pricing: '/pricing',
  checkout: '/checkout',
  postDetail: '/post/:nameid',
  updatePostReject: '/update-rejected/:nameid',
  //account
  account: '/account',
  accountPosts: '/account/posts',
  accountNotification: '/account/notification',
  accountProfile: '/account/profile',
  accountUpdateProfile: 'updateProfile',
  accountTransaction: '/account/transaction',
  accountAddress: '/account/payment',
  accountChangePassword: '/account/password',
  accountPrivacySetting: '/setting/privacy',
  //admin
  admin: '/admin',
  adminPosts: '/admin/posts',
  adminDashboard: '/admin/dashboard',
  adminListings: '/admin/listings',
  adminUsers: '/admin/users',
  adminTransactions: '/admin/transactions',
  adminAuctions: '/admin/auctions',
  adminReports: '/admin/reports',
  adminSettings: '/admin/settings'
} as const
